# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
    identifier = "ai"
    name       = "AI"
    url        = "/categories/AI/"
    weight     = 2

    [main.params]
        icon = "robot"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/wodaixin"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "mail"
    name       = "E-mail"
    url        = "mailto:wodaixin@gmail.com"

    [social.params]
        icon = "brand-gmail"

[[social]]
    identifier = "wechat"
    name       = "WeChat"
    url        = "#wechat"

    [social.params]
        icon = "brand-wechat"